/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ventasbd.aplicacion;

import java.text.SimpleDateFormat;
import java.util.Collection;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ventasbd.dao.exception.ErrorBorradoVenta;
import ventasbd.dao.exception.ErrorConexionBD;
import ventasbd.modelo.Item;
import ventasbd.modelo.SistemaVentas;
import ventasbd.modelo.Venta;

/**
 *
 * @author jdelarosa
 */
public class VentasJFrame extends javax.swing.JFrame {

    /**
     * Creates new form VentasJFrame
     */
    String cabecera [] = {"cantidad","Descripción","Importe por unidad"};
    DefaultTableModel tabla;
    SistemaVentas sistemaVentas;
    public VentasJFrame() {
         try {
            
            sistemaVentas = new SistemaVentas();
        }
        catch(ErrorConexionBD e) {
            System.out.println("Error de conexión con BD");
            return;
        }
        initComponents();
        
            String  a[][] = {{" "," "," "},{" "," "," "},{" "," "," "},{" "," "," "},{" "," "," "}};
            tabla = new DefaultTableModel(a ,cabecera);
            jTable1.setModel(tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("venta  numero");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Fecha");

        jLabel3.setText("Suma");

        jLabel4.setText("IVA");

        jLabel5.setText("Total");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Borrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.setToolTipText("");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(40, 40, 40)
                        .addComponent(jButton2)
                        .addGap(39, 39, 39)
                        .addComponent(jButton3))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
       try{  
        
            Venta venta = sistemaVentas.venta(Integer.parseInt(jTextField1.getText()));
              if (venta != null) {
                  jTextField2.setText(new SimpleDateFormat("dd-MM-yyyy").format(venta.getFecha()));
                  tabla = new DefaultTableModel(venta.obtenerItems(),cabecera);
                  jTable1.setModel(tabla);
                  jTextField3.setText(Float.toString(venta.calcularImporte()));
                  jTextField4.setText(Float.toString(venta.calcularIVA()));
                  jTextField5.setText(Float.toString(venta.calcularTotal()));
              }
              else{
                  String  a[][] = {{" "," "," "},{" "," "," "},{" "," "," "},{" "," "," "},{" "," "," "},{" "," "," "}};
                  tabla = new DefaultTableModel(a ,cabecera);
                  jTable1.setModel(tabla);
                  jTextField2.setText(" ");
                  jTextField3.setText(" ");
                  jTextField4.setText(" ");
                  jTextField5.setText(" ");
              }
                  
       }catch (Exception e)
       {
               System.out.println("Error con BD");
       }
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      try {          
         Venta venta = new Venta(Integer.parseInt(jTextField1.getText()));
         jTextField2.setText(new SimpleDateFormat("dd-MM-yyyy").format(venta.getFecha()));
                  
         
         int i = 0 ;
         String vacia = " ";
         
         while (vacia.compareTo((String)jTable1.getValueAt(i,0))!=0){
            
             // System.out.println("-" + jTable1.getValueAt(0,0)+"-");
                 int cantidad= Integer.parseInt(((String)jTable1.getValueAt(i,0)).trim());
                 String concepto =(String)jTable1.getValueAt(i,1);
                 float importe = Float.parseFloat(((String)jTable1.getValueAt(i,2)).trim());      
                 venta.anadirItem(new Item(cantidad,concepto,importe));
                 i++;
         }
         sistemaVentas.nuevaVenta(venta);
         jTextField3.setText(Float.toString(venta.calcularImporte()));
         jTextField4.setText(Float.toString(venta.calcularIVA()));
         jTextField5.setText(Float.toString(venta.calcularTotal()));
      
         JOptionPane.showMessageDialog(this, " venta creada ",
                "Confirmación", JOptionPane.PLAIN_MESSAGE);
         
        
      }
      catch (Exception e){
          
          JOptionPane.showMessageDialog(this, "datos de venta incorrectos",
                "Error", JOptionPane.ERROR_MESSAGE);
            
      }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        Venta venta = sistemaVentas.venta(Integer.parseInt(jTextField1.getText()));
          if (JOptionPane.showConfirmDialog(this,
                    "La venta se perderá para siempre ¿desea continuar?",
                    "Atención", JOptionPane.YES_NO_OPTION,
                    JOptionPane.WARNING_MESSAGE) == JOptionPane.YES_OPTION) {
              try {
                    sistemaVentas.borrarVenta(venta);
              } catch (ErrorBorradoVenta ex) {
                   JOptionPane.showMessageDialog(this, "no se pudo borrar venta",
                  "Error", JOptionPane.ERROR_MESSAGE);
              }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            
              try {          
                    Venta venta = new Venta(Integer.parseInt(jTextField1.getText()));
                    jTextField2.setText(new SimpleDateFormat("dd-MM-yyyy").format(venta.getFecha()));
                  
         
                    int i = 0 ;
                    String vacia = " ";
         
                    while (vacia.compareTo((String)jTable1.getValueAt(i,0))!=0){
            
                        int cantidad= Integer.parseInt(((String)jTable1.getValueAt(i,0)).trim());
                        String concepto =(String)jTable1.getValueAt(i,1);
                        float importe = Float.parseFloat(((String)jTable1.getValueAt(i,2)).trim());      
                        venta.anadirItem(new Item(cantidad,concepto,importe));
                        i++;
                        
                    }
                    
                    Venta ventaABorrar = sistemaVentas.venta(Integer.parseInt(jTextField1.getText()));
                    try {
                        sistemaVentas.borrarVenta(ventaABorrar);
                    } catch (ErrorBorradoVenta ex) {
                        JOptionPane.showMessageDialog(this, "no se pudo borrar venta",
                        "Error", JOptionPane.ERROR_MESSAGE);
                    }
                    sistemaVentas.nuevaVenta(venta);
                    jTextField3.setText(Float.toString(venta.calcularImporte()));
                    jTextField4.setText(Float.toString(venta.calcularIVA()));
                    jTextField5.setText(Float.toString(venta.calcularTotal()));
      
                    JOptionPane.showMessageDialog(this, " venta creada ",
                                "Confirmación", JOptionPane.PLAIN_MESSAGE);
         
        
               }
               catch (Exception e){
                   e.printStackTrace();
                        JOptionPane.showMessageDialog(this, "datos de venta incorrectos",
                        "Error", JOptionPane.ERROR_MESSAGE);            
                }
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentasJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 SistemaVentas sistemaVentas = null;
                 try {
                   sistemaVentas = new SistemaVentas();
                 }
                 catch(ErrorConexionBD e) {
                        System.out.println("Error de conexión con BD");
              
                 }
        
                new VentasJFrame().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
